version: 2
models:
# dim tests
- name: dim_customer
  columns:
    - name: customer_id
      tests:
        - not_null
        - unique
- name: dim_orders
  columns:
    - name: order_id
      tests:
        - not_null
        - unique
    - name: customer_id
      tests:
        - not_null
        - unique
- name: dim_supplier
  columns:
    - name: supplier_id
      tests:
        - not_null
        - unique
- name: dim_part
  columns:
    - name: part_id
      tests:
        - not_null
        - unique
- name: fact_lineitem
  columns:
    - name: order_id
      tests:
        - not_null
        - unique
    - name: part_id
      tests:
        - not_null
        - unique
    - name: supplier_id
      tests:
        - not_null
        - unique
