version: 2
models:
- name: stg_tpch_sf1_customer
  columns:
    - name: customer_id
      tests:
        - not_null
- name: stg_tpch_sf1_orders
    columns:
      - name: order_id
        tests:
          - not_null
